spring:
  profiles:
    active: local
---

spring:
  profiles: local
  kafka:
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10
    admin:
      properties:
        bootstrap.servers: localhost:29092
        key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
    template:
      default-topic: library-events
---

spring:
  profiles: nonprod
  kafka:
    topic: library-events
    template:
      default-topic: library-events
    producer:
      bootstrap-servers: localhost:9095,localhost:9096,localhost:9097
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      ssl:
        trust-store-location: file:<location>/client.truststore.jks
        trust-store-password: password
        key-store-location: file:<location>/client.keystore.jks
        key-store-password: password
      properties:
        max:
          block:
            ms: 3000
        ssl.endpoint.identification.algorithm:
        security:
          protocol: SSL
---

spring:
  profiles: prod
  kafka:
    producer:
      bootstrap-servers: prod:9092, prod:9093, prod:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
